services:
  app:
    build: .
    ports:
      - "8000:8000" # FastAPI
      - "8501:8501" # Streamlit
    volumes:
      - .:/app
      - fastembed_cache:/root/.cache/fastembed # Cache for FastEmbed models
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_URL=http://ollama:11434
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_URL=${GROQ_URL}
    depends_on:
      - qdrant
      - ollama

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  qdrant_data:
  fastembed_cache:
  ollama_data:
